motor_limits:
  lower_leg_motor:
    frd: [-4.17, 4.17]
    fld: [-4.17, 4.17]
    rrd: [-4.17, 4.17]
    rld: [-4.17, 4.17]
  upper_leg_motor:
    fru: [-3.14, 3.14]
    flu: [-3.14, 3.14]
    rru: [-3.14, 3.14]
    rlu: [-3.14, 3.14]
  hip_motor:
    frh: [-1.57, 1.57]
    flh: [-1.57, 1.57]
    rrh: [-1.57, 1.57]
    rlh: [-1.57, 1.57]
