motor_limits:
  motor1:
    min_position: -1.57
    max_position: 1.57
    stop_on_exceed: true
  motor2:
    min_position: -1.57
    max_position: 1.57
    stop_on_exceed: true 
  motor3:
    min_position: -1.57
    max_position: 1.57
    stop_on_exceed: true 
