# 
# policy_path:  "pre_train/isaacgym/exported/policies/policy_1.pt"
policy_path: "/home/ray/quatest_ws/src/controller/rl_quadruped_controller/rl_quadruped_controller/pre_train/policy_gym.pt"
xml_path: "scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

kps: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
kds: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

default_angles: [0.1, 0.785, -1.57, -0.1, 0.785, -1.57, 0.1, -0.785, 1.57, -0.1, -0.785, 1.57]

lin_vel_scale: 1.0
ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.1
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 48

cmd_init: [0.5, 0, 0.0]